### Series in Pandas

#### Creating a Series

In [3]:
import numpy as np
import pandas as pd

In [3]:
lables = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {1:10, 2:20, 3:30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(my_list, index = lables)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(arr, index = lables)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

#### DataFrames

In [13]:
#creating a DataFrames

data = {'Name':['John', 'Anna', 'Peter', 'Linda'],
       'Age':[28, 34, 29, 42],
       'City':['New York', 'Paris', 'Berlin', 'London'],
       'Salary':[65000, 70000, 62000, 85000]
       }

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
# df2

columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [21]:
#Accessing column
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [22]:
#Accessing multiple columns
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [23]:
# Adding New Column
df2["Designation"] = ["Doctor", "Eng.", "Doctor", "Eng."]

In [24]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [25]:
#Removing Column from DataFrame
df2.drop("Designation", axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [30]:
df2.drop("Designation", axis = 1, inplace = True) #inplace=True actually removes the data from the memory, whereas without it drop just shows the snapshot.

KeyError: "['Designation'] not found in axis"

In [28]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df2.drop(["City","Salary"], axis = 1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [31]:
#Removing Rows from DataFrame
df2.drop(0, axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [34]:
#Accessing the Rows
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [36]:
#Selecting subset of rows and columns

df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [37]:
#Conditional Selection

#Selection with age>30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [41]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

#### Missing Data

##### Finding Missing Data

In [52]:
data = {
    "A" : [1, 2, np.nan, 4, 5],
    "B" : [1, 2, 3, 4, 5],
    "C" : [1, 2, 3, np.nan, np.nan],
    "D" : [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [47]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [49]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [50]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [51]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [53]:
#Removing missing data (Works on basis of rows)

df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [54]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [56]:
df.dropna(thresh = 1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [57]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [58]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [60]:
values = {'A' : 0, 'B' : 100, 'C' : 300, 'D' : 400}
df.fillna(value = values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [61]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

#### Mearging, Joining & Concatenation

In [65]:
employees = pd.DataFrame({
    'employee_id' : [1,2,3,4,5],
    'name' : ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department' : ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id' : [1,2,3,6,7],
    'salary' : [60000, 80000, 65000, 70000, 90000],
    'bonous' : [5000, 10000, 7000, 8000, 12000]
})

In [66]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [67]:
salaries

   employee_id  salary  bonous
0            1   60000    5000
1            2   80000   10000
2            3   65000    7000
3            6   70000    8000
4            7   90000   12000

In [68]:
#Merging
pd.merge(employees, salaries, on = "employee_id")

   employee_id   name department  salary  bonous
0            1   John         HR   60000    5000
1            2   Anna         IT   80000   10000
2            3  Peter    Finance   65000    7000

In [69]:
pd.merge(employees, salaries, on = "employee_id", how = 'left')

   employee_id   name department   salary   bonous
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [70]:
pd.merge(employees, salaries, on = "employee_id", how = "outer")

   employee_id   name department   salary   bonous
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [71]:
pd.merge(employees, salaries, on = "employee_id", how = "right")

   employee_id   name department  salary  bonous
0            1   John         HR   60000    5000
1            2   Anna         IT   80000   10000
2            3  Peter    Finance   65000    7000
3            6    NaN        NaN   70000    8000
4            7    NaN        NaN   90000   12000

In [72]:
#Concatination 

df1 = pd.DataFrame({
    'A' : ['A0','A1', 'A2'],
    'B' : ['B0', 'B1', 'B2'],
    'C' : ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    "A" : ['A3', 'A4', 'A5'],
    "B" : ['B3', 'B4', 'B5'],
    "C" : ["C3", "C4", "C5"]
})

In [76]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [78]:
pd.concat([df1, df2], axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [80]:
#Joining two DataFrames

df1 = pd.DataFrame({
    'name' : ['Alice','Bob', 'Charlie']
}, index = [1, 2, 3])

df2 = pd.DataFrame({
    'score' : [85, 90, 75]
}, index = [2, 3, 4])

In [81]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [82]:
df2

   score
2     85
3     90
4     75

In [83]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [84]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [85]:
df1.join(df2, how = "outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

##### Group By Aggregation

In [4]:
data = {
    'Category' : ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store' : ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales' : [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity' : [10, 15, 12, 18, 8, 20, 15, 25],
    'Date' : pd.date_range('2026-10-11', periods = 8)
}
df = pd.DataFrame(data)

In [87]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2026-10-11
1        B    S1    200        15 2026-10-12
2        A    S2    150        12 2026-10-13
3        B    S2    250        18 2026-10-14
4        A    S1    120         8 2026-10-15
5        B    S2    180        20 2026-10-16
6        A    S2    200        15 2026-10-17
7        B    S1    300        25 2026-10-18

In [94]:
#Group by category and calculate the sum of Sales
cat = df.groupby("Category")['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [93]:
#Group by Store and Calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [5]:
#Group by multiple columns
#Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

#### Aggregation

In [6]:
df['Sales'].mean()

np.float64(187.5)

In [7]:
df['Sales'].median()

np.float64(190.0)

In [10]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [9]:
df['Sales'].max()

np.int64(300)

In [11]:
#standard deviation
df['Sales'].std()

np.float64(66.06274074155351)

In [17]:
#To get multiple results at one (Can't find mode)

df['Sales'].agg(['mean', 'min', 'max', 'sum', 'count', 'std'])

mean      187.500000
min       100.000000
max       300.000000
sum      1500.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64

### Pivot Table

In [20]:
data = {
    'Date' : pd.date_range('2026-10-12', periods = 20),
    'Product' : ['A', 'B', 'C', 'D'] * 5,
    'Region' : ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales' : np.random.randint(100, 1000, 20),
    'Units' : np.random.randint(10,100,20),
    'Rep' : ['John', 'Mary', 'Bob', 'Alice','John', 'Mary', 'Bob', 'Alice','John', 'Mary', 'Bob', 'Alice','John', 'Mary', 'Bob', 'Alice','John', 'Mary', 'Bob', 'Alice'],
}

df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q ' + df['Date'].dt.quarter.astype(str)

In [21]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2026-10-12       A   East    673     51   John  October     Q 4
1  2026-10-13       B   West    993     77   Mary  October     Q 4
2  2026-10-14       C  North    681     60    Bob  October     Q 4
3  2026-10-15       D  South    652     54  Alice  October     Q 4
4  2026-10-16       A   East    766     93   John  October     Q 4
5  2026-10-17       B   West    596     64   Mary  October     Q 4
6  2026-10-18       C  North    198     36    Bob  October     Q 4
7  2026-10-19       D  South    509     28  Alice  October     Q 4
8  2026-10-20       A   East    540     31   John  October     Q 4
9  2026-10-21       B   West    472     29   Mary  October     Q 4
10 2026-10-22       C  North    835     70    Bob  October     Q 4
11 2026-10-23       D  South    570     90  Alice  October     Q 4
12 2026-10-24       A   East    185     48   John  October     Q 4
13 2026-10-25       B   West    404     89   Mary  October     Q 4
14 2026-10-26       C  North    924     25    Bob  October     Q 4
15 2026-10-27       D  South    977     75  Alice  October     Q 4
16 2026-10-28       A   East    781     72   John  October     Q 4
17 2026-10-29       B   West    494     11   Mary  October     Q 4
18 2026-10-30       C  North    626     92    Bob  October     Q 4
19 2026-10-31       D  South    407     38  Alice  October     Q 4

In [24]:
pd.pivot_table(df, values = 'Sales', index = 'Region', columns = 'Product', aggfunc = 'median')

Product      A      B      C      D
Region
East     673.0    NaN    NaN    NaN
North      NaN    NaN  681.0    NaN
South      NaN    NaN    NaN  570.0
West       NaN  494.0    NaN    NaN

In [25]:
pivot2 = pd.pivot_table(df, values = ['Sales', 'Units'], index = 'Region', columns = 'Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     589.0    NaN    NaN    NaN  59.0   NaN   NaN   NaN
North      NaN    NaN  652.8    NaN   NaN   NaN  56.6   NaN
South      NaN    NaN    NaN  623.0   NaN   NaN   NaN  57.0
West       NaN  591.8    NaN    NaN   NaN  54.0   NaN   NaN

#### Cross Tabs

In [26]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

## Operations

In [45]:
df1 = pd.DataFrame({
    'A' : [1,2,3,4,5],
    'B' : [10, 20, 30, 40, 50],
    'C' : [100, 200, 300, 400, 500]
})

In [28]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [30]:
df1.shape

(5, 3)

In [31]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [33]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [34]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [35]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

#### DataFrames Applying Functions

In [36]:
def square (x):
    return x**2

In [46]:
df1['D'] = df1['B'].apply(lambda x:x**2)

In [47]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500